security:
    encoders:
        App\Domain\User\Entity\User:
            algorithm: auto
        App\Domain\UserClient\Entity\UserClient:
            algorithm: auto


    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Domain\User\Entity\User
                property: email
        app_client_provider:
          entity:
            class: App\Domain\UserClient\Entity\UserClient
            property: uuid
        # used to reload user from session & other features (e.g. switch_user)
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Http\Security\LoginFormAuthenticator
                    - App\Http\Security\ClientAuthenticator
                entry_point: App\Http\Security\LoginFormAuthenticator
            logout:
                path: app_logout
        client:
          anonymous: true
          lazy: true
          provider: app_client_provider
          guard:
            authenticators:
              - App\Http\Security\ClientAuthenticator
            entry_point: App\Http\Security\ClientAuthenticator
          logout:
            path: app_logout

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
         - { path: ^/app, roles: ROLE_COMPANY }
         - { path: /logout, roles: IS_AUTHENTICATED_FULLY }
         - { path: /login, roles: [IS_ANONYMOUS, IS_AUTHENTICATED_FULLY]  }
         - { path: ^/reset, roles: IS_ANONYMOUS }
         - { path: /, roles: [IS_ANONYMOUS, IS_AUTHENTICATED_FULLY] }
